In [3]:
import numpy as np

In [ ]:
# Q1

# (a) Reverse the array
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed:", arr[::-1])

# (b) Flatten the array
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Flatten using ravel:", array1.ravel())
print("Flatten using flatten:", array1.flatten())

# (c) Compare arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print("Arrays equal:", np.array_equal(arr1, arr2))

# (d) Most frequent value and indices
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_val = values[np.argmax(counts)]
    indices = np.where(arr == max_val)[0]
    return max_val, indices

print("X most frequent:", most_frequent(x))
print("Y most frequent:", most_frequent(y))

# (e) Sum operations on matrix
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum of all:", np.sum(gfg))
print("Row-wise sum:", np.sum(gfg, axis=1))
print("Column-wise sum:", np.sum(gfg, axis=0))

# (f) Matrix operations
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("Diagonal sum:", np.trace(n_array))
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print("Inverse:\n", np.linalg.inv(n_array))
print("Determinant:", np.linalg.det(n_array))



Reversed: [5 4 6 3 2 1]
Flatten using ravel: [1 2 3 2 4 5 1 2 3]
Flatten using flatten: [1 2 3 2 4 5 1 2 3]
Arrays equal: True
X most frequent: (np.int64(1), array([0, 5, 7, 8, 9]))
Y most frequent: (np.int64(1), array([0, 1, 2]))
Sum of all: 45
Row-wise sum: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]
Diagonal sum: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [5]:


# (g) Matrix multiplication and covariance

# --- First pair ---
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

print("Matrix product 1:\n", np.dot(p1, q1))  # or p1 @ q1
print("Covariance 1:\n", np.cov(p1.T, q1.T))  # same shape → works


# --- Second pair ---
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

print("Matrix product 2:\n", np.dot(p2, q2))

# Covariance between flattened versions (same length)
print("Covariance 2 (flattened):\n", np.cov(p2.flatten(), q2.flatten()))


# (h) Inner, outer, cartesian product
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print("Inner product:\n", np.inner(x, y))
print("Outer product:\n", np.outer(x.flatten(), y.flatten()))

# Cartesian product
from itertools import product
cartesian = np.array(list(product(x.flatten(), y.flatten())))
print("Cartesian product:\n", cartesian)


Matrix product 1:
 [[16 19]
 [26 31]]
Covariance 1:
 [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
Matrix product 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance 2 (flattened):
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]
Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
# Q2

# (a)
array = np.array([[1, -2, 3], [-4, 5, -6]])

# i. Absolute value
print("Absolute:\n", np.abs(array))

# ii. Percentiles
flat = array.flatten()
print("Flattened 25th, 50th, 75th:", np.percentile(flat, [25, 50, 75]))
print("Column percentiles:\n", np.percentile(array, [25, 50, 75], axis=0))
print("Row percentiles:\n", np.percentile(array, [25, 50, 75], axis=1))

# iii. Mean, Median, Std Dev
print("Flattened mean/median/std:", flat.mean(), np.median(flat), flat.std())
print("Column-wise mean/median/std:", array.mean(axis=0), np.median(array, axis=0), array.std(axis=0))
print("Row-wise mean/median/std:", array.mean(axis=1), np.median(array, axis=1), array.std(axis=1))

# (b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Trunc:", np.trunc(a))
print("Rounded:", np.round(a))


Absolute:
 [[1 2 3]
 [4 5 6]]
Flattened 25th, 50th, 75th: [-3.5 -0.5  2.5]
Column percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Flattened mean/median/std: -0.5 -0.5 3.8622100754188224
Column-wise mean/median/std: [-1.5  1.5 -1.5] [-1.5  1.5 -1.5] [2.5 3.5 4.5]
Row-wise mean/median/std: [ 0.66666667 -1.66666667] [ 1. -4.] [2.05480467 4.78423336]
Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
#Q3

# (a)
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted array:", np.sort(array))
print("Indices of sorted:", np.argsort(array))
print("4 smallest:", np.sort(array)[:4])
print("5 largest:", np.sort(array)[-5:][::-1])

# (b)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
is_integer = array == array.astype(int)
print("Integer elements:", array[is_integer])
print("Float elements:", array[~is_integer])


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted: [0 3 4 1 5 2 6]
4 smallest: [10 16 16 52]
5 largest: [453  62  54  52  16]
Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]
